# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Last Updated at January, 2018
email:
description:
#    Federal Reserve Bank of Minneapolis,
#    Research Department,
#    90 Hennepin Avenue,
#    Minneapolis, MN 55401
#    Department of Econometrics and Business Statistics,
#    Monash University,
#    900 Dandenong Road, Caulfield East, Victoria
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
#"http://difang-huang.github.io" # the base hostname & protocol for your site
github_username:  #difang-huang

# Build settings
markdown: kramdown
