# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Difang Huang
email: difang.huang@outlook.com
description:
      Monash University,
      900 Dandenong Rd,
      Caulfield East, VIC 3145
#    Federal Reserve Bank of Minneapolis,
#    Research Department,
#    90 Hennepin Avenue,
#    Minneapolis, MN 55401
#    Department of Econometrics and Business Statistics,

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://difang-huang.github.io" # the base hostname & protocol for your site
github_username:  #difang-huang

# Build settings
markdown: kramdown
