# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Difang Huang
email: difang@hku.hk
description: Faculty of Business and Economics<\br>University of Hong Kong
      

# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://difang-huang.github.io" # the base hostname & protocol for your site
github_username: #difang-huang

# Build settings
markdown: kramdown
